### PR TITLE
[clang-tidy] use nodiscard

### PR DESCRIPTION
**Pull request by neheb**
Introduced in C++17. It replaces gcc's warn_unused_result.

Found with modernize-use-nodiscard.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Is there any value in repeating the attribute in overrides?

**Comment by neheb** [comment]
AFAIK, g++ and clang do not inherit nodiscard in overrides.

In other news, it seems g++6 does not like nodiscard. Although if I remember correctly, g++6 doesn't support C++17 fully.

**Comment by MaxKellermann** [comment]
I looked it up - indeed, the C++ standard doesn't say that any function attributes are inherited. This is unfortunate, because doing so would make a lot of sense!

GCC6 is indeed a problem, but I think it would be ok to drop GCC6 support now. I always try to keep MPD compatible with the default compiler in Debian Stable and Ubuntu LTS. Debian Stable has GCC8 (used to be GCC6, this is why MPD requires compatibility with 6), and Ubuntu LTS has GCC 7. Support for `nodiscard` was added in version 7, so this PR is ok.

**Comment by neheb** [comment]
Hrm maybe this was not too correct.

As I see, src/util/Compiler.h has several defines for gcc attributes. Maybe a better solution would have been to replace

```
gcc_warn_unused_result __attribute__((warn_unused_result))
```

with

```
gcc_warn_unused_result [[nodiscard]]
```

But then again that's just pandering to old compilers.

**Pull request merged**
