### PR TITLE
Spell correction

### PR DESCRIPTION
**Pull request by 0x15BA88FF**
Spell correction  of "Thas" to "That"

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Bad commit message.

**Comment by pascall-de-creator** [comment]
Sorry

**Comment by MaxKellermann** [comment]
So.... will you write a proper one?

**Comment by 0x15BA88FF** [comment]
I've updated the commit message, is this alright?

**Comment by SoongNoonien** [comment]
> I've updated the commit message, is this alright?

Unfortunately you only changed the title of the pull request. To change the actual commit message you could issue a `git commit --amend -m "Spell correction"` and then a `git push --force` in your local clone. But I think a better commit message would be something like "doc/plugins.rst: fix spelling", in this case the first command would be `git commit --amend -m "doc/plugins.rst: fix spelling"`.

**Comment by MaxKellermann** [comment]
A merge commit in the PR branch ... this gets worse now.

**Comment by 0x15BA88FF** [comment]
Sorry, I'm having issues amending the commit but i just cant seem to get my signatures to work on Github codespace.

Sorry for the inconveniences, feel free to make the change yourself

**Pull request closed without merging**
