### PR TITLE
array conversions

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by MaxKellermann** [comment]
```
../../src/event/SignalMonitor.cxx: In function ‘void SignalMonitorFinish()’:
../../src/event/SignalMonitor.cxx:171:20: error: use of deleted function ‘std::array<std::atomic<bool>, 64>& std::array<std::atomic<bool>, 64>::operator=(std::array<std::atomic<bool>, 64>&&)’
  171 |  signal_pending = {};
      |                    ^
In file included from /usr/include/c++/10/tuple:39,
                 from /usr/include/c++/10/functional:54,
                 from /usr/include/c++/10/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/10/algorithm:74,
                 from ../../src/event/SignalMonitor.cxx:39:
/usr/include/c++/10/array:94:12: note: ‘std::array<std::atomic<bool>, 64>& std::array<std::atomic<bool>, 64>::operator=(std::array<std::atomic<bool>, 64>&&)’ is implicitly deleted because the default definition would be ill-formed:
   94 |     struct array
      |            ^~~~~
/usr/include/c++/10/array:94:12: error: use of deleted function ‘std::atomic<bool>& std::atomic<bool>::operator=(const std::atomic<bool>&)’
In file included from ../../src/event/SignalMonitor.cxx:36:
/usr/include/c++/10/atomic:73:13: note: declared here
   73 |     atomic& operator=(const atomic&) = delete;
      |             ^~~~~~~~
```

**Comment by neheb** [comment]
hrm compiles on fedora 35. Maybe this'll fix it.

**Comment by neheb** [comment]
oh I see. USE_SIGNALFD is defined.

**Comment by MaxKellermann** [comment]
Yes, that's one of my builds with `-Dsignalfd=false` (to compile code which is usually only used on non-Linux, which I don't have). I guess I should add such a build to the CI.

**Comment by neheb** [comment]
just compiled with that flag. works.

**Comment by MaxKellermann** [comment]
Not here:
```
FAILED: src/event/libevent.a.p/SignalMonitor.cxx.o 
ccache c++ -Isrc/event/libevent.a.p -Isrc/event -I../../src/event -Isrc -I../../src -I. -I../.. -I/usr/include -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -Os -g -ffast-math -ftree-vectorize -Wcast-qual -Wdouble-promotion -Wmissing-declarations -Wshadow -Wunused -Wvla -Wwrite-strings -fno-threadsafe-statics -fmerge-all-constants -Wcomma-subscript -Wextra-semi -Wmismatched-tags -Woverloaded-virtual -Wsign-promo -Wvolatile -Wvirtual-inheritance -Wno-non-virtual-dtor -Wsuggest-override -fvisibility=hidden -ffunction-sections -fdata-sections -D_GNU_SOURCE -fPIC -DBOOST_ALL_NO_LIB -MD -MQ src/event/libevent.a.p/SignalMonitor.cxx.o -MF src/event/libevent.a.p/SignalMonitor.cxx.o.d -o src/event/libevent.a.p/SignalMonitor.cxx.o -c ../../src/event/SignalMonitor.cxx
In file included from /usr/include/c++/10/bits/char_traits.h:39,
                 from /usr/include/c++/10/string:40,
                 from /usr/include/c++/10/bits/locale_classes.h:40,
                 from /usr/include/c++/10/bits/ios_base.h:41,
                 from /usr/include/c++/10/streambuf:41,
                 from /usr/include/c++/10/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/10/iterator:66,
                 from ../../src/util/IntrusiveList.hxx:37,
                 from ../../src/event/SocketEvent.hxx:26,
                 from ../../src/event/SignalMonitor.cxx:25:
/usr/include/c++/10/bits/stl_algobase.h: In instantiation of ‘typename __gnu_cxx::__enable_if<(! std::__is_scalar<_Tp>::__value), void>::__type std::__fill_a1(_ForwardIterator, _ForwardIterator, const _Tp&) [with _ForwardIterator = std::atomic<bool>*; _Tp = std::atomic<bool>; typename __gnu_cxx::__enable_if<(! std::__is_scalar<_Tp>::__value), void>::__type = void]’:
/usr/include/c++/10/bits/stl_algobase.h:914:21:   required from ‘void std::__fill_a(_FIte, _FIte, const _Tp&) [with _FIte = std::atomic<bool>*; _Tp = std::atomic<bool>]’
/usr/include/c++/10/bits/stl_algobase.h:1065:20:   required from ‘_OutputIterator std::__fill_n_a(_OutputIterator, _Size, const _Tp&, std::random_access_iterator_tag) [with _OutputIterator = std::atomic<bool>*; _Size = long unsigned int; _Tp = std::atomic<bool>]’
/usr/include/c++/10/bits/stl_algobase.h:1094:29:   required from ‘_OI std::fill_n(_OI, _Size, const _Tp&) [with _OI = std::atomic<bool>*; _Size = long unsigned int; _Tp = std::atomic<bool>]’
/usr/include/c++/10/array:117:20:   required from ‘void std::array<_Tp, _Nm>::fill(const value_type&) [with _Tp = std::atomic<bool>; long unsigned int _Nm = 64; std::array<_Tp, _Nm>::value_type = std::atomic<bool>]’
../../src/event/SignalMonitor.cxx:171:27:   required from here
/usr/include/c++/10/bits/stl_algobase.h:861:11: error: use of deleted function ‘std::atomic<bool>& std::atomic<bool>::operator=(const std::atomic<bool>&)’
  861 |  *__first = __value;
      |  ~~~~~~~~~^~~~~~~~~
In file included from ../../src/event/SignalMonitor.cxx:36:
/usr/include/c++/10/atomic:73:13: note: declared here
   73 |     atomic& operator=(const atomic&) = delete;
      |             ^~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by neheb** [comment]
reproduced now. Fixed.

**Pull request merged**
