### PR TITLE
algorithm changes

### PR DESCRIPTION
**Pull request by neheb**
[cppcheck] use std::accumulate

Found with useStlAlgorithm

Basic godbolt test indicates accumulate to be better:

https://godbolt.org/z/nefgs7

Signed-off-by: Rosen Penev <rosenp@gmail.com>

 [cppcheck] use std::find_if

Found with useStlAlgorithm

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Faster too:

```
for range result 178120743 took 0.001670 ms
std::accumulate result 178120743 took 0.000220 ms
```

**Comment by MaxKellermann** [comment]
```
../../src/db/plugins/upnp/Directory.hxx:44:18: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
```

**Comment by neheb** [comment]
weird. XCode throws a different error:

```
../src/output/plugins/OSXOutputPlugin.cxx:47:10: fatal error: 'optional' file not found
```

I'll fix that as well.

**Comment by neheb** [comment]
rebased.

**Comment by neheb** [comment]
Closing since it seems this won't be merged.

**Pull request closed without merging**
