### PR TITLE
Add "added" timestamp to song database

### LINKED ISSUE #378: [database] add "date added" attribute for songs
MPD should track for changes and add a "date added" attribute, so one can look for new songs in the database.

### PR DESCRIPTION
**Pull request by jcorporation**
addedtime is only set to mtime, if a new song is added to the database.

Code for proxy plugin is missing, this needs a patch for libmpdclient.

closes #378

### CODE REVIEW

**Comment by jcorporation** [comment]
Should addedtime fallback to modifiedsince for things like sorting?

**Comment by MaxKellermann** [comment]
I don't quite get it. Why is it initialized with mtime? If it's the mtime, what's the point of having a separate field, because we already have mtime?

**Comment by jcorporation** [comment]
i initiailize it with mtime and leave it untouched in further database updates. Idea is to have a timestamp that does not change after a song was added to the database.

mtime changes on each change if the file, even only a tag is corrected. With addtime there is a timestamp a mpd client can use to sort by date added and not only last modified.

**Comment by MaxKellermann** [comment]
Do people really modify the song files, and is that important enough to add global unavoidable overhead to the protocol, MPD's memory consumption and to the database?
At best, this feature is misnamed/misdocumented, because it's not when this song was added to MPD, but the last time is was modified *before* it was added.

**Comment by jcorporation** [comment]
Yes, I change tags regularly, if I see that a file was tagged falsely. Typo in a tag etc.

Without the added attribute you can not get a list of newly added songs, only a list of last modified songs.

We can initialize the added with the current timestamp, then the behavior is as documented.

**Comment by MaxKellermann** [comment]
We shouldn't design a feature to match documentation, we should rather decide which value is more useful and then fix both code and documentation.

**Comment by jcorporation** [comment]
I am unsure what of both options is the better one. I can perfectly life with both.

**Pull request merged**
