### PR TITLE
Problem with GCC 7.2 and mounts

### PR DESCRIPTION
**Pull request by FlashSystems**
GCC 7.2 does not generate a correct assignment for mnt->mounted_database = db. I'm not sure why but using a function fixes this.

Without this function the mounted_database property is not set and the mountpoint does not work as expected.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This looks fishy. If you don't know why your change works, then it's not a good change.
Does removing the `gcc_malloc` fix the issue as well?

**Comment by FlashSystems** [comment]
Removing `gcc_malloc` from `Directory::CreateChild` did the trick. I was not aware that the attribute of the function returning the pointer could be the problem here. Thank you for pointing this out.

**Comment by MaxKellermann** [comment]
Neither did I, that was just a guess. This means that this is a GCC bug.

**Comment by FlashSystems** [comment]
Hm, than adding
```
#if GCC_CHECK_VERSION(7,2)
#  define gcc_malloc __attribute__((malloc))
#else
#  define gcc_malloc
#endif
```
to `Compiler.hxx` would be a better solution. Maybe there are more problems lingering...

**Comment by MaxKellermann** [comment]
12085038881a4aba94c74b7104c5090bc777001e
Indeed this `malloc` attribute was wrong and that's not a GCC bug, because aliasing can also mean that somewhere else there lurks a pointer to the same object, even if it's not directly reachable.
I checked the other `malloc` attributes left in the MPD sources, and the others appear to be correct.

**Pull request closed without merging**
