### PR TITLE
RunCurl test: added fs_dep to fix link error

### PR DESCRIPTION
**Pull request by geneticdrift**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Which linker error? RunCurl doesn't use this library, so if you see a linker problem, the cause must be somewhere else

**Comment by geneticdrift** [comment]
I get this link error building with tests from master head:
<pre>
[134/202] Linking target test/RunCurl
FAILED: test/RunCurl 
clang++  -o test/RunCurl test/RunCurl.p/RunCurl.cxx.o test/RunCurl.p/ShutdownHandler.cxx.o -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,--start-group src/lib/curl/libcurl.a liblog.a src/event/libevent.a src/io/uring/liburing.a src/io/libio.a src/thread/libthread.a src/net/libnet.a src/system/libsystem.a src/util/libutil.a /usr/lib/libfmt.so /usr/lib/liburing.so /usr/lib/libcurl.so -Wl,--end-group -pthread
/usr/bin/ld: src/io/libio.a.p/FileReader.cxx.o: in function `FileReader':
<unknown>:103: undefined reference to `AllocatedPath::~AllocatedPath()'
/usr/bin/ld: src/io/libio.a.p/FileReader.cxx.o: in function `FileReader::Skip(long)':
/home/devel/dev/mpd.build.clang/../mpd.my_github.fork/src/fs/AllocatedPath.hxx:283: undefined reference to `Path::ToUTF8[abi:cxx11]() const'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
[155/202] Linking target mpd
ninja: build stopped: subcommand failed.
</pre>

**Comment by geneticdrift** [comment]
Checked again, and this error happens when compiling with clang but not when compiling with gcc.

```
C compiler for the host machine: clang (clang 14.0.6 "clang version 14.0.6")
C linker for the host machine: clang ld.bfd 2.38
C++ compiler for the host machine: clang++ (clang 14.0.6 "clang version 14.0.6")
C++ linker for the host machine: clang++ ld.bfd 2.38
```
```
C compiler for the host machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39.0
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (GCC) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.39.0
```

**Comment by MaxKellermann** [comment]
This PR was just a workaround for some weirdly designed circular dependencies between libio.a and libsystem.a; the workaround was not a good solution. Meanwhile, I have tried to find a better solution; please try if the problem is solved in the master branch.

**Pull request closed without merging**
