### PR TITLE
replace assert.h with cassert

### PR DESCRIPTION
**Pull request by neheb**
These were deprecated in C++14.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Does the C++14 standard guarantee that the top-level namespace symbols are made available by the C++ headers?
I made the same complaint already last month: https://github.com/MusicPlayerDaemon/MPD/pull/753#issuecomment-582548250 but you did not reply to that, and instead closed the PR.

**Comment by neheb** [comment]
This seems to be the standard: http://eel.is/c++draft/depr.c.headers#other

Modified quote:

```
Every C header, each of which has a name of the form <name.h>, behaves as if each name placed in the standard library namespace by the corresponding <cname> header is placed within the global namespace scope,
```

In that other PR, I changed it to std::lround. Speaking of which, I should probably change the title...

**Comment by MaxKellermann** [comment]
From this standard text, I read the exact opposite, invalidating your PR!
The text you cited says that the C header (which MPD currently uses without this PR) defines symbols in the global namespace. But it does **not** say that the C++ variants (which MPD uses *with* this PR) populate the global namespace.
Quite the opposite:
> The header <cstdlib> assuredly provides its declarations and definitions within the namespace std.
It may also provide these names within the global namespace

Note the wording: "It may", but that's not a guarantee - that's merely telling the C++ developer that those symbols may already be defined, so they're not available; but it does not legalize actually using those symbols, because they're an implementation detail.

**Comment by neheb** [comment]
Hrm OK I'll partially change the PR.

assert.h and cassert are the same, according to the C++11 and C++17 standards: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0063r3.html (19.3). I'll see about the others.

**Comment by neheb** [comment]
Changed to only replace assert.h.

**Comment by neheb** [comment]
Changed several more.

stdarg, stddef, and stdint place several types in the std:: namespace, but I don't think it makes sense to replace all of them. Changes would be massive:

```
git grep size_t | wc -l
1402
```

**Comment by MaxKellermann** [comment]
Thanks, those commit messages are good work and help readers understand the change!

**Pull request merged**
