### PR TITLE
Tag pool missing lock in TagBuilder::RemoveType

### PR DESCRIPTION
**Pull request by geneticdrift**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This PR contains text which is missing in the commit message

**Comment by geneticdrift** [comment]
> This PR contains text which is missing in the commit message

I don't see it. Can you please tell me what is missing?

**Comment by MaxKellermann** [comment]
> > This PR contains text which is missing in the commit message
> 
> I don't see it. Can you please tell me what is missing?

```
Unsafe access indicated by valgrind:

==74245== Possible data race during read of size 1 at 0x1ABB5D28 by thread #1
==74245== Locks held: none
==74245==    at 0x202B04: tag_pool_put_item(TagItem*) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x201D6C: TagBuilder::RemoveType(TagType) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1A0032: playlist::ClearSongIdTag(unsigned int, TagType) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x15CB69: handle_cleartagid(Client&, Request, Response&) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x15B92E: command_process(Client&, unsigned int, char*) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x16D751: Client::ProcessLine(char*) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x16DCFA: Client::OnSocketInput(void*, unsigned long) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1C26CA: BufferedSocket::ResumeInput() (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1C2847: BufferedSocket::OnSocketReady(unsigned int) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1C56E1: EventLoop::Run() (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x15A3DB: MainConfigured(CommandLineOptions const&, ConfigData const&) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x15AA1A: MainOrThrow(int, char**) (in /home/devel/mpd.master/bin/mpd)
==74245== 
==74245== This conflicts with a previous write of size 1 by thread #4
==74245== Locks held: 3, at addresses 0x354580 0x1A1B6EB0 0x1C449320
==74245==    at 0x202B16: tag_pool_put_item(TagItem*) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x2007F0: Tag::Clear() (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1877B9: MusicChunkInfo::~MusicChunkInfo() (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1870E3: MusicBuffer::Return(MusicChunk*) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x205952: MultipleOutputs::CheckPipe() (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x18E2C3: PlayerControl::WaitOutputConsumed(std::unique_lock<std::mutex>&, unsigned int) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x18C0D1: Player::Run() (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x18D9E6: PlayerControl::RunThread() (in /home/devel/mpd.master/bin/mpd)
==74245==  Address 0x1abb5d28 is 8 bytes inside a block of size 25 alloc'd
==74245==    at 0x4843908: malloc (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==74245==    by 0x2029F8: tag_pool_get_item(TagType, std::basic_string_view<char, std::char_traits<char> >) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x20199E: TagBuilder::AddItemUnchecked(TagType, std::basic_string_view<char, std::char_traits<char> >) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x201C1F: TagBuilder::AddItem(TagType, char const*) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1DEF69: CurlInputStream::OnHeaders(unsigned int, std::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&&) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x1D3ED7: CurlResponseHandlerAdapter::WriteFunction(char*, unsigned long, unsigned long, void*) (in /home/devel/mpd.master/bin/mpd)
==74245==    by 0x6E16B7B: ??? (in /usr/lib/libcurl.so.4.8.0)
==74245==    by 0x6DF8B8C: ??? (in /usr/lib/libcurl.so.4.8.0)
==74245==    by 0x6E293AC: ??? (in /usr/lib/libcurl.so.4.8.0)
==74245==    by 0x6E0F166: ??? (in /usr/lib/libcurl.so.4.8.0)
==74245==    by 0x6E12906: ??? (in /usr/lib/libcurl.so.4.8.0)
==74245==    by 0x6E12AAE: curl_multi_socket_action (in /usr/lib/libcurl.so.4.8.0)
==74245==  Block was alloc'd by thread #2
```

You posted this text in the PR, so you decided it's important. If it's important, it should be in a commit message. PR texts are only in GitHub's proprietary database and will be lost when GitHub is gone one day, only commit messages remain forever to help us understand a commit.

**Comment by MaxKellermann** [comment]
I don't want to read PR texts; the existence of one is a red flag for me. Commit messages are for reviewers.

**Comment by geneticdrift** [comment]
OK. No more PR descriptions, and all relevant text in commit messages. (I have made the same mistake in the stickers PR #1659, hope it's not to much trouble. Let me know if you want me to re-do it).

**Comment by MaxKellermann** [comment]
First commit cherry-picked to v0.23.x: abb28593ce3a5c176123edfe7729e6d8c379903a
The second commit looks a bit ugly (old coding style with underscores in C++ method names), adds overhead (by adding an implicit `this` parameter to all methods) and leaves the class copyable, so it actually makes the code less safe.

**Pull request closed without merging**
