### PR TITLE
OS X mixer (master)

### PR DESCRIPTION
**Pull request by matthewleon**
Following up on https://github.com/MusicPlayerDaemon/MPD/pull/100

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This is not a merge.

**Comment by matthewleon** [comment]
> This is not a merge.

Understood. I'll try this as a merge.

**Comment by matthewleon** [comment]
Sorry for the rebase. This should be a merge now.

**Comment by MaxKellermann** [comment]
Thanks, much better. This avoids merge conflicts.

**Pull request merged**
