### PR TITLE
[clang-tidy] use auto where appropriate

### PR DESCRIPTION
**Pull request by neheb**
Found with modernize-use-auto

Signed-off-by: Rosen Penev <rosenp@gmail.com>

My understanding is the following:

auto c = (const char *) -> lhs is const char *
const auto *c = (const char *) -> lhs is const char *
const auto c = (const char *) -> lhs is const char * const

Removing the * makes the type clearer IMO.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Build breakage:
```
../../src/util/UriUtil.cxx: In function ‘std::__cxx11::string uri_remove_auth(const char*)’:
../../src/util/UriUtil.cxx:93:16: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   slash = auth + strlen(auth);
           ~~~~~^~~~~~~~~~~~~~
```

**Comment by neheb** [comment]
weird. I don't get that locally. Fixed anyways.

**Comment by neheb** [comment]
Oh I see the problem. strchr returns char *. std::strchr returns const char *.

**Comment by MaxKellermann** [comment]
```
../../src/decoder/plugins/AudiofileDecoderPlugin.cxx: In function ‘AFvirtualfile* setup_virtual_fops(AudioFileInputStream&)’:
../../src/decoder/plugins/AudiofileDecoderPlugin.cxx:132:44: error: use of ‘vf’ before deduction of ‘auto’
  auto vf = (AFvirtualfile *)malloc(sizeof(*vf));
                                            ^~
```
Do you compile before you submit a PR?

**Comment by neheb** [comment]
I remember encountering this error. I thought I fixed it. Maybe I did so in a different branch. I'll update this when I can.

**Comment by neheb** [comment]
Fixed and rebased. Travis passes.

**Comment by MaxKellermann** [comment]
I don't think any of this is really an improvement.

**Pull request closed without merging**
