### PR TITLE
src/output: add algorithm for finding usable AudioFormat

### PR DESCRIPTION
**Pull request by ibmibmibm**
* Add ComWorker to run all COM relative function in same thread.
* Add Interrupt interface.
* Reopen device on error.
* Use WinEvent for as a condition_variable without lock.

See https://github.com/MusicPlayerDaemon/MPD/issues/967

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Can you split this commit, so I can cherry-pick the fix for the stable branch?
I wouldn't like to merge such a huge commit with so many major possibly-breaking changes into the stable branch.

**Comment by MaxKellermann** [comment]
Sorry for letting you wait for so long, and thanks for putting so much work into splitting the PR.
I had difficulties with several of your commits because my GCC-mingw build doesn't have threading enabled; this works in GCC only through pthread emulation. Therefore, std::future/std::promise is unavailable, as well as std::mutex (which is why I've been carrying the `using Mutex = CriticalSection` around for so long).
I wish GCC had proper C++ standard library support for native Win32 threading... but all these years, that didn't happen.

I don't want to use pthread emulation for MPD/Windows builds, so I'll try to figure out how to do it without those C++ threading features.

And I'll try to backport the format detection code to the stable branch without the threading changes. This is the most important change here.

Meanwhile, I've cherry-picked a few trivial commits. It would be great if you could keep your PR branch rebased on my master branch.

**Comment by ibmibmibm** [comment]
I've implemented std::future and std::promise for mingw32 without pthread.
The implements are inspired by [microsoft stl](https://github.com/microsoft/STL/blob/main/stl/inc/future)

**Comment by MaxKellermann** [comment]
Cherry-picked to v0.22 with some cleanups
da642b289049836f2d89b65726ef1aa5229b5f82

**Pull request closed without merging**
