### PR TITLE
clang-tidy: add explicit deleted constructors

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Why?

**Comment by neheb** [comment]
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-special-member-functions.html

I would guess this is to avoid different compilers having different behaviors.

**Comment by MaxKellermann** [comment]
What compiler would have a different behavior? The behavior is defined by the standard.
If a class has a move constructor/operator, the copy constructor/operator is implicitly deleted. That's fine. I don't agree that it should be explicitly deleted. The standard defines exactly the behavior I want there. Explicitly deleting these only creates unnecessary code noise (boilerplate code) and reduces code readability. The syntax for those operators/constructors is too complicated and error prone already. I want less of that, not more.
There are a few good pieces in your change: for example, `class InputStream` is copyable, but it should not be. Deleting its copy constructor/operator should be enough to take account for all sub classes. The proxy database changes are good.
What I don't understand is why you declare defaulted destructors. That part is not explained in the core guidelines. They say you should always declare all 5, but doesn't explain what use a defaulted destructor is.

**Comment by neheb** [comment]
I initially declared the destructors as deleted. Then it did not compile.

**Comment by neheb** [comment]
Note that the check has several options. I think AllowMissingMoveFunctionsWhenCopyIsDeleted and AllowSoleDefaultDtor would be what you want.

**Comment by neheb** [comment]
Did just that.

**Pull request merged**
