### PR TITLE
revert to {} to work around gcc bug

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Bad commit message. Which bug?

**Comment by neheb** [comment]
Travis is failing on it actually. With GCC 6.

**Comment by neheb** [comment]
Updated.

**Comment by MaxKellermann** [comment]
But is this really a bug? Did you get any confirmation from the GCC project?
I have a feeling that the compiler error is correct, so I'm curious for your analysis.

**Comment by neheb** [comment]
It's most definitely a bug, either with older GCC or older libstdc++ since it does not happen with newer versions. I think it compiles with clang + libc++ as well.

**Comment by MaxKellermann** [comment]
Do you understand the error message? Do you know why the compiler complains?
The complaint is based on the C++ standard.
Differences between compiler versions are legal/possible, because some compilers (and their standard libraries) may choose to make methods/constructors `noexcept` even if the standard does not mandate it. And maybe a newer libstdc++ version has made certain constructors `noexcept`, which are called implicitly here. Did you consider this?

**Comment by neheb** [comment]
Yeah I've seen that with the math functions. They're constexpr in GCC even though the standard doesn't mention anything.

All I know is that it's failing on the buildbots currently.

**Pull request closed without merging**
