### PR TITLE
Init Cary Audio branch.

### PR DESCRIPTION
**Pull request by Cad101**
For Cary Audio product.

### CODE REVIEW

**Comment by Cad101** [comment]
Hi Max,

I have sent this to my software engineers. They will work to send it to you as you suggest.

Thanks,

­­­­­­­­­­­­­­­­Billy Wright | President | LinkedIn<http://www.linkedin.com/in/billyw>
CARY AUDIO
6301 Chapel Hill Road | Raleigh, NC 27607
919-355-0010 PHONE
www.caryaudio.com<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1098035568]<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_663992051]<https://www.facebook.com/caryaudiodesign>  [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2045415681] <https://twitter.com/caryaudio>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_656425996] <https://www.instagram.com/caryaudio/>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_216617693] <https://www.linkedin.com/company/1190271?trk=tyah>

Click here<http://www.caryaudio.com/emaillist.html> to sign up to receive our monthly enewsletters!

**Comment by MaxKellermann** [comment]
More than a year later, I havn't heard back from your software engineers. What is happening?

**Comment by Cad101** [comment]
Hi Max,

I am not sure what you mean. I thought everything was settled long ago. If there is something we were supposed to do and have not done it, please let me know. I will follow up immediately.

I will also forward this e-mail to my software guys so they can see it.

Thanks,

­­­­­­­­­­­­­­­­Billy Wright | President | LinkedIn<http://www.linkedin.com/in/billyw>
CARY AUDIO
6301 Chapel Hill Road | Raleigh, NC 27607
919-355-0010 PHONE
www.caryaudio.com<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1098035568]<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_663992051]<https://www.facebook.com/caryaudiodesign>  [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2045415681] <https://twitter.com/caryaudio>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_656425996] <https://www.instagram.com/caryaudio/>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_216617693] <https://www.linkedin.com/company/1190271?trk=tyah>

Click here<http://www.caryaudio.com/emaillist.html> to sign up to receive our monthly enewsletters!

**Comment by MaxKellermann** [comment]
> I thought everything was settled long ago. If there is something we were supposed to do and have not done it, please let me know.

I thought you were interested in getting your improvements merged into the official MPD, and I made suggestions on how to do it properly; your reply was:

> They will work to send it to you as you suggest. 

Nothing was sent to me.

Of course, you're not obliged to "do it properly" (as long as you strictly obey the license). Separating out the individual improvements and getting them merged may take your engineers quite some time.

But on the other hand, there are huge long-term advantages for you: by reducing the gap between your MPD fork and the official MPD, it will be very easy to update to newer MPD versions, taking advantage of new features and bug fixes.

The way you've been doing it until now will make that very hard. Every MPD update takes lots of time, for development and testing; eventually adding up to much more than doing it now once and for all. And having a better code organization is obviously a good investment.

**Comment by Cad101** [comment]
Hi Max,

I will send this to the software guys. As far as I know, everything is being done correctly. I do not want any issues. If they need to send you something, I will make sure they do it.

Thanks,

­­­­­­­­­­­­­­­­Billy Wright | President | LinkedIn<http://www.linkedin.com/in/billyw>
CARY AUDIO
6301 Chapel Hill Road | Raleigh, NC 27607
919-355-0010 PHONE
www.caryaudio.com<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1098035568]<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_663992051]<https://www.facebook.com/caryaudiodesign>  [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2045415681] <https://twitter.com/caryaudio>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_656425996] <https://www.instagram.com/caryaudio/>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_216617693] <https://www.linkedin.com/company/1190271?trk=tyah>

Click here<http://www.caryaudio.com/emaillist.html> to sign up to receive our monthly enewsletters!

**Comment by MaxKellermann** [comment]
I think this PR is going nowhere.
Please tell your software guys to submit proper PRs - this code dump cannot be merged as-is.
If your software guys need help, they shall contact me.

**Comment by Cad101** [comment]
Hi Max,

I will forward your e-mail to my software guys. I will be back in touch soon.

Thanks,



­­­­­­­­­­­­­­­­Billy Wright | President | LinkedIn<http://www.linkedin.com/in/billyw>
CARY AUDIO
6301 Chapel Hill Road | Raleigh, NC 27607
919-355-0010 PHONE
www.caryaudio.com<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1098035568]<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_663992051]<https://www.facebook.com/caryaudiodesign>  [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2045415681] <https://twitter.com/caryaudio>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_656425996] <https://www.instagram.com/caryaudio/>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_216617693] <https://www.linkedin.com/company/1190271?trk=tyah>

Click here<http://www.caryaudio.com/emaillist.html> to sign up to receive our monthly enewsletters!

**Comment by Cad101** [comment]
Hi Max,

My lead software engineer sent me an e-mail with the following:

He will submit two new "pull requests" to you before the end of March, once for DMS-500/AiOS and once for DMS-600/550.

Let me know if this sounds good.

Thanks,

­­­­­­­­­­­­­­­­Billy Wright | President | LinkedIn<http://www.linkedin.com/in/billyw>
CARY AUDIO
6301 Chapel Hill Road | Raleigh, NC 27607
919-355-0010 PHONE
www.caryaudio.com<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1098035568]<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_663992051]<https://www.facebook.com/caryaudiodesign>  [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2045415681] <https://twitter.com/caryaudio>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_656425996] <https://www.instagram.com/caryaudio/>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_216617693] <https://www.linkedin.com/company/1190271?trk=tyah>

Click here<http://www.caryaudio.com/emaillist.html> to sign up to receive our monthly enewsletters!

From: Billy Wright
Sent: Thursday, February 20, 2020 11:44 AM
To: MusicPlayerDaemon/MPD <reply@reply.github.com>; MusicPlayerDaemon/MPD <MPD@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MusicPlayerDaemon/MPD] Init Cary Audio branch. (#272)

Hi Max,

I will forward your e-mail to my software guys. I will be back in touch soon.

Thanks,



­­­­­­­­­­­­­­­­Billy Wright | President | LinkedIn<http://www.linkedin.com/in/billyw>
CARY AUDIO
6301 Chapel Hill Road | Raleigh, NC 27607
919-355-0010 PHONE
www.caryaudio.com<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1098035568]<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_663992051]<https://www.facebook.com/caryaudiodesign>  [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2045415681] <https://twitter.com/caryaudio>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_656425996] <https://www.instagram.com/caryaudio/>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_216617693] <https://www.linkedin.com/company/1190271?trk=tyah>

Click here<http://www.caryaudio.com/emaillist.html> to sign up to receive our monthly enewsletters!

**Comment by MaxKellermann** [comment]
> Hi Max, My lead software engineer sent me an e-mail with the following: He will submit two new "pull requests" to you before the end of March, once for DMS-500/AiOS and once for DMS-600/550. Let me know if this sounds good.

Sounds very good! Tell him that two things are important:
- separate things must be in separate commits; don't mix more than one change in one commit
- each commit must be documented

**Comment by Cad101** [comment]
Great. I will let him know your comments.

Thanks,

­­­­­­­­­­­­­­­­Billy Wright | President | LinkedIn<http://www.linkedin.com/in/billyw>
CARY AUDIO
6301 Chapel Hill Road | Raleigh, NC 27607
919-355-0010 PHONE
www.caryaudio.com<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1098035568]<http://www.caryaudio.com/>

[/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_663992051]<https://www.facebook.com/caryaudiodesign>  [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_2045415681] <https://twitter.com/caryaudio>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_656425996] <https://www.instagram.com/caryaudio/>   [/Users/Katie/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_216617693] <https://www.linkedin.com/company/1190271?trk=tyah>

Click here<http://www.caryaudio.com/emaillist.html> to sign up to receive our monthly enewsletters!

**Pull request closed without merging**
