### PR TITLE
Fix build with Boost 1.67.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes https://github.com/MusicPlayerDaemon/MPD/issues/265.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Sorry, that is a Boost bug. Wrong place to fix this.

**Comment by ilovezfs** [comment]
@MaxKellermann regardless of whether you consider it a "Boost bug" it seems undesirable for mpd to be unable to build with Boost 1.67.

**Comment by ilovezfs** [comment]
@MaxKellermann are you suggesting that every downstream distribution of Boost needs to backport https://github.com/boostorg/lockfree/commit/12726cda009a855073b9bedbdce57b6ce7763da2 ?

**Comment by MaxKellermann** [comment]
That looks like the fix, so yes, vanilla 1.67.0 should not be used by anybody. Either keep using 1.66 or patch 1.67. That's better than patching each and every application using Boost.

But WTF, this patch is 4 months old, and hasn't found its way into the Boost version released just a few days ago. There appears to be something wrong with Boost's patch management.

**Comment by ilovezfs** [comment]
@MaxKellermann yeah ... tell me about it. This happens like every time :(

**Comment by MaxKellermann** [comment]
Ha, that's the dirty real world!
Shit happens, but then you clean up, but don't cover it.

**Pull request closed without merging**
