### PR TITLE
New command countplaylist

### PR DESCRIPTION
**Pull request by jcorporation**
Count the number of songs and their total playtime in the playlist.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
The documentation show describe the response, e.g. show an example response.
I don't like the command name, it's confusing - this sounds like counting playlists, but it actually counts the contents of the playlist. Maybe `playlistsize`? Slightly better, but not perfect. Can you come up with a better name? `playlisttotals`? (still ugly)

**Comment by jcorporation** [comment]
`playlistsize` sounds good for me.

**Comment by jcorporation** [comment]
> Another option could be playlistlength, which is also used in [status response](https://mpd.readthedocs.io/en/stable/protocol.html#command-status) to indicate the length of the playlist (queue).

We calculate the length and the duration with this command. `playlistlength` seems to explicit for me. I would vote for playlistsize, but it is the decision of @MaxKellermann.

**Comment by jcorporation** [comment]
> The documentation show describe the response, e.g. show an example response.

Added a example.

**Comment by jcorporation** [comment]
Renamed to playlistlength

**Pull request merged**
