### PR TITLE
macOS: fix Bonjour build

### PR DESCRIPTION
**Pull request by Nyx0uf**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Please improve the commit message, explaining why suddenly that other framework is needed instead of "dnssd".

**Comment by Nyx0uf** [comment]
I don't know why, nor since when, I did not find any explanation.

There's no more dnssd framework, instead there is a `/usr/lib/system/libsystem_dnssd.dylib` but we can't directly link to it because it yields an error saying we have to link with `System.framework`.

**Comment by MaxKellermann** [comment]
There must be some documentation explaining which library shall be linked. I don't know that, because I don't have any Apple products. But I worry about having things in the MPD repository which nobody understands, so I'd like to have explanations in commits like that.

**Comment by Nyx0uf** [comment]
Yeah I understand. I searched on Apple dev forums, didn't find.
The only doc I found don't mention what to link : https://developer.apple.com/documentation/dnssd
I also looked at the `dns_sd.h` header file but there's nothing more there :/

Since when Zeroconf has been disabled for macOS ?

**Comment by MaxKellermann** [comment]
Can't review this PR without pointers to Apple documentation.

**Pull request closed without merging**
